#!/bin/bash
#SBATCH --job-name=calculate_save_energetics_no_ice_u3c4_keps        #Set the job name to "JobExample1"
#SBATCH -C cpu
#SBATCH --qos=regular 
#SBATCH --time=21:00:00          
#SBATCH --nodes=1
#SBATCH --ntasks=128
#SBATCH --ntasks-per-node=128
#SBATCH --account=m4572
#SBATCH --output=calculate_save_energetics_no_ice_u3c4_keps_001.out         #Send stdout/err to "Example1Out.[jobID]"

module load conda
conda activate xroms

# Define variables
INPUT_PATH='/pscratch/sd/b/bundzis/Beaufort_ROMS_idealized_jet_scratch/roms_avg_no_ice_500m_w_dvd_constant_forcing_u3c4_keps_*.nc'
OUT_PATH='/global/cfs/cdirs/m4572/bundzis/roms_idealized_beaufort_jet/Post_process_data/roms_energetics_2hr_500m_const_forc_no_ice_u3c4_keps_001.nc'

# Call the python script
python3 calculate_save_energetics.py \
    --avg_file "$INPUT_PATH" \
    --min_xi 1 \
    --max_xi 399 \
    --min_eta 140 \
    --max_eta 420 \
    --z_slice 200.0 \
    --output "$OUT_PATH"

echo "Analysis complete for $OUT_PATH"


